[profile.default]
src = "contracts"
out = "artifacts"
libs = ["node_modules", "lib"]
solc = "0.8.19"
remappings = [
    "@ensdomains/=node_modules/@ensdomains/",
    "@eth-optimism/=node_modules/@eth-optimism/",
    "@helix-foundation/=node_modules/@helix-foundation/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat/=node_modules/hardhat/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config