name: OP-ECO CI Tests

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    strategy:
      fail-fast: true
      
    name: Eslint, prettier and solhint
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: build project
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command

      - name: check lint
        uses: borales/actions-yarn@v4
        with:
          cmd: format # will run `yarn format` command

  tests:
    strategy:
      fail-fast: true

    name: Test Suite
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: build project
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command

      - name: Run Test
        uses: borales/actions-yarn@v4
        with:
          cmd: test # will run `yarn build` command
  check:
    strategy:
      fail-fast: true

    name: Optimism Foundry Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
          
      - name: Install dependencies
        run: yarn install

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test